import PDFDocument from 'pdfkit';

// Helper to create a PDF buffer
const generatePdfBuffer = (doc: PDFKit.PDFDocument): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', err => reject(err));
  });
};

export const pdfService = {
  async createHandbookPdf(handbook: Record<string, unknown>): Promise<Buffer> {
    const doc = new PDFDocument({ margin: 50 });
    
    const title = typeof handbook.title === 'string' ? handbook.title : 'MANAK Handbook';
    const category = typeof handbook.category === 'string' ? handbook.category : 'N/A';
    const status = typeof handbook.status === 'string' ? handbook.status : 'N/A';
    const description = typeof handbook.description === 'string' ? handbook.description : '';
    const metadata = typeof handbook.metadata === 'object' ? handbook.metadata : null;

    // Title
    doc.fontSize(24).font('Helvetica-Bold').text(title, { align: 'center' });
    doc.moveDown();
    
    // Metadata
    doc.fontSize(12).font('Helvetica').text(`Category: ${category}`, { align: 'right' });
    doc.text(`Status: ${status}`, { align: 'right' });
    doc.text(`Generated: ${new Date().toLocaleString()}`, { align: 'right' });
    doc.moveDown(2);
    
    // Description
    if (description) {
      doc.fontSize(14).font('Helvetica-Bold').text('Description');
      doc.fontSize(12).font('Helvetica').text(description, { align: 'justify' });
      doc.moveDown(2);
    }
    
    // Additional Metadata (JSONB)
    if (metadata && Object.keys(metadata).length > 0) {
      doc.fontSize(14).font('Helvetica-Bold').text('Metadata Details');
      doc.fontSize(12).font('Helvetica').text(JSON.stringify(metadata, null, 2));
      doc.moveDown();
    }
    
    // Footer
    doc.fontSize(10).text('Generated by MANAK Intelligence', 50, doc.page.height - 50, { align: 'center' });
    
    doc.end();
    return generatePdfBuffer(doc);
  },

  async createReportPdf(report: Record<string, unknown>): Promise<Buffer> {
    const doc = new PDFDocument({ margin: 50 });
    
    const title = typeof report.title === 'string' ? report.title : 'MANAK Report';
    const reportType = typeof report.report_type === 'string' ? report.report_type : 'N/A';
    const status = typeof report.status === 'string' ? report.status : 'N/A';
    const description = typeof report.description === 'string' ? report.description : '';
    const metadata = typeof report.metadata === 'object' ? report.metadata : null;

    // Title
    doc.fontSize(24).font('Helvetica-Bold').text(title, { align: 'center' });
    doc.moveDown();
    
    // Metadata
    doc.fontSize(12).font('Helvetica').text(`Report Type: ${reportType}`, { align: 'right' });
    doc.text(`Status: ${status}`, { align: 'right' });
    doc.text(`Generated: ${new Date().toLocaleString()}`, { align: 'right' });
    doc.moveDown(2);
    
    // Description
    if (description) {
      doc.fontSize(14).font('Helvetica-Bold').text('Report Summary');
      doc.fontSize(12).font('Helvetica').text(description, { align: 'justify' });
      doc.moveDown(2);
    }
    
    // Additional Details
    if (metadata && Object.keys(metadata).length > 0) {
      doc.fontSize(14).font('Helvetica-Bold').text('Report Findings & Details');
      doc.fontSize(12).font('Helvetica').text(JSON.stringify(metadata, null, 2));
      doc.moveDown();
    }
    
    // Footer
    doc.fontSize(10).text('Generated by MANAK Intelligence', 50, doc.page.height - 50, { align: 'center' });
    
    doc.end();
    return generatePdfBuffer(doc);
  },

  async createMultiHandoutPdf(standards: { code: string; title: string; type: string; year: string }[]): Promise<Buffer> {
    const doc = new PDFDocument({ margin: 50 });
    
    // Title Page
    doc.fontSize(28).font('Helvetica-Bold').text('MANAK Selected Handouts', { align: 'center' });
    doc.moveDown(2);
    doc.fontSize(14).font('Helvetica').text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
    doc.text(`Total Documents: ${standards.length}`, { align: 'center' });
    doc.moveDown(4);
    
    // Index
    doc.fontSize(18).font('Helvetica-Bold').text('Included Documents');
    doc.moveDown();
    standards.forEach((s, i) => {
      doc.fontSize(12).font('Helvetica').text(`${i + 1}. ${s.code} - ${s.title}`);
    });
    
    // Pages for each standard
    standards.forEach((s, i) => {
      doc.addPage();
      doc.fontSize(20).font('Helvetica-Bold').text(s.code, { align: 'center' });
      doc.moveDown();
      doc.fontSize(16).font('Helvetica-Bold').text(s.title, { align: 'center' });
      doc.moveDown(2);
      
      doc.fontSize(12).font('Helvetica').text(`Type: ${s.type}`, { align: 'right' });
      if (s.year) {
        doc.text(`Year: ${s.year}`, { align: 'right' });
      }
      doc.moveDown(2);
      
      doc.fontSize(14).font('Helvetica-Bold').text('Summary / Notes');
      doc.fontSize(12).font('Helvetica').text('This document is a consolidated handout summary generated from MANAK intelligence. Please refer to the full document for technical specifications and legally binding clauses.', { align: 'justify' });
      
      doc.fontSize(10).text(`Page ${i + 2} of ${standards.length + 1}`, 50, doc.page.height - 50, { align: 'center' });
    });
    
    doc.end();
    return generatePdfBuffer(doc);
  }
};
